# Generated by Django 5.0 on 2023-12-15 18:15

from django.db import migrations
from django.contrib.auth.models import User
from django.db import transaction


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("auth", "0005_alter_user_last_login_null"),
    ]

    def add_data(apps, schema_migration):
        # Not really needed but... it save time :D
        data = [
            {
                "first_name": "Rachel",
                "last_name": "Barber",
                "email": "accumsan.sed@hotmail.edu",
                "city": "Bastia",
                "age": 21,
                "gender": "male",
            },
            {
                "first_name": "Nicole",
                "last_name": "Evans",
                "email": "aliquam.enim@icloud.org",
                "city": "Pontarlier",
                "age": 29,
                "gender": "male",
            },
            {
                "first_name": "Jacob",
                "last_name": "Johnson",
                "email": "non.lacinia@icloud.ca",
                "city": "Saint-Quentin",
                "age": 60,
                "gender": "female",
            },
            {
                "first_name": "Cairo",
                "last_name": "Bailey",
                "email": "nec.cursus.a@google.ca",
                "city": "Le Puy-en-Velay",
                "age": 43,
                "gender": "female",
            },
            {
                "first_name": "Warren",
                "last_name": "Finley",
                "email": "sit@aol.com",
                "city": "Abbeville",
                "age": 40,
                "gender": "male",
            },
            {
                "first_name": "Joy",
                "last_name": "Erickson",
                "email": "nunc.sit.amet@aol.ca",
                "city": "Le Havre",
                "age": 40,
                "gender": "male",
            },
            {
                "first_name": "Oliver",
                "last_name": "Browning",
                "email": "adipiscing.fringilla@yahoo.net",
                "city": "Rezé",
                "age": 48,
                "gender": "female",
            },
            {
                "first_name": "Warren",
                "last_name": "Green",
                "email": "id.mollis.nec@icloud.edu",
                "city": "Aubervilliers",
                "age": 35,
                "gender": "female",
            },
            {
                "first_name": "Asher",
                "last_name": "Clark",
                "email": "eget@google.edu",
                "city": "Compiègne",
                "age": 28,
                "gender": "male",
            },
            {
                "first_name": "Damon",
                "last_name": "Park",
                "email": "semper.pretium@outlook.net",
                "city": "Colmar",
                "age": 55,
                "gender": "male",
            },
            {
                "first_name": "Duncan",
                "last_name": "Delgado",
                "email": "leo.vivamus.nibh@protonmail.net",
                "city": "Chalon-sur-Saône",
                "age": 25,
                "gender": "female",
            },
            {
                "first_name": "Alfonso",
                "last_name": "Bender",
                "email": "mauris@icloud.com",
                "city": "Saint-Malo",
                "age": 33,
                "gender": "female",
            },
            {
                "first_name": "Hadassah",
                "last_name": "Mason",
                "email": "metus.in@aol.edu",
                "city": "Colomiers",
                "age": 31,
                "gender": "male",
            },
            {
                "first_name": "Byron",
                "last_name": "Nash",
                "email": "sem.eget@hotmail.couk",
                "city": "Saint-Dizier",
                "age": 45,
                "gender": "male",
            },
            {
                "first_name": "Callie",
                "last_name": "Forbes",
                "email": "nunc.quisque@protonmail.edu",
                "city": "Saint-Denis",
                "age": 26,
                "gender": "female",
            },
            {
                "first_name": "Lev",
                "last_name": "Sweet",
                "email": "amet.ante.vivamus@hotmail.ca",
                "city": "Tournefeuille",
                "age": 29,
                "gender": "female",
            },
            {
                "first_name": "Ursula",
                "last_name": "Hebert",
                "email": "et.eros.proin@icloud.org",
                "city": "Brive-la-Gaillarde",
                "age": 59,
                "gender": "male",
            },
            {
                "first_name": "Herman",
                "last_name": "Dyer",
                "email": "enim@aol.edu",
                "city": "Toulouse",
                "age": 39,
                "gender": "male",
            },
            {
                "first_name": "Nina",
                "last_name": "Richardson",
                "email": "et.malesuada@google.edu",
                "city": "Abbeville",
                "age": 25,
                "gender": "female",
            },
            {
                "first_name": "Illana",
                "last_name": "Hodges",
                "email": "proin.nisl@protonmail.edu",
                "city": "Sarreguemines",
                "age": 19,
                "gender": "female",
            },
            {
                "first_name": "Yeo",
                "last_name": "Orr",
                "email": "convallis@icloud.com",
                "city": "Chartres",
                "age": 51,
                "gender": "male",
            },
            {
                "first_name": "Finn",
                "last_name": "Barber",
                "email": "sagittis.augue.eu@google.couk",
                "city": "Calais",
                "age": 22,
                "gender": "male",
            },
            {
                "first_name": "Mannix",
                "last_name": "Rivers",
                "email": "eu.metus@google.couk",
                "city": "Troyes",
                "age": 53,
                "gender": "female",
            },
            {
                "first_name": "Zeph",
                "last_name": "Stephens",
                "email": "malesuada.ut@aol.ca",
                "city": "Vitry-sur-Seine",
                "age": 30,
                "gender": "female",
            },
            {
                "first_name": "Walker",
                "last_name": "Vaughan",
                "email": "pede.et.risus@icloud.couk",
                "city": "Reims",
                "age": 48,
                "gender": "male",
            },
            {
                "first_name": "Erica",
                "last_name": "Rush",
                "email": "ac.metus@google.net",
                "city": "Aurillac",
                "age": 32,
                "gender": "male",
            },
            {
                "first_name": "Aphrodite",
                "last_name": "Acosta",
                "email": "vitae.purus.gravida@hotmail.net",
                "city": "Brive-la-Gaillarde",
                "age": 20,
                "gender": "female",
            },
            {
                "first_name": "Gregory",
                "last_name": "Kent",
                "email": "sapien@outlook.net",
                "city": "Dreux",
                "age": 27,
                "gender": "female",
            },
            {
                "first_name": "Celeste",
                "last_name": "Sampson",
                "email": "purus@yahoo.couk",
                "city": "Nîmes",
                "age": 54,
                "gender": "male",
            },
            {
                "first_name": "Jael",
                "last_name": "Ellis",
                "email": "adipiscing.non@hotmail.org",
                "city": "Calais",
                "age": 40,
                "gender": "male",
            },
            {
                "first_name": "Yoshi",
                "last_name": "Grant",
                "email": "ac.ipsum@outlook.edu",
                "city": "Chalon-sur-Saône",
                "age": 49,
                "gender": "female",
            },
            {
                "first_name": "Briar",
                "last_name": "Hartman",
                "email": "aliquam.adipiscing@aol.com",
                "city": "Lens",
                "age": 31,
                "gender": "female",
            },
            {
                "first_name": "Malachi",
                "last_name": "Robertson",
                "email": "maecenas.iaculis@google.couk",
                "city": "Bastia",
                "age": 19,
                "gender": "male",
            },
            {
                "first_name": "Omar",
                "last_name": "Chaney",
                "email": "nibh@aol.org",
                "city": "Laon",
                "age": 56,
                "gender": "male",
            },
            {
                "first_name": "Brielle",
                "last_name": "Neal",
                "email": "morbi.non@yahoo.couk",
                "city": "Dreux",
                "age": 41,
                "gender": "female",
            },
            {
                "first_name": "Chancellor",
                "last_name": "Brennan",
                "email": "non.lobortis.quis@hotmail.org",
                "city": "Ajaccio",
                "age": 54,
                "gender": "female",
            },
            {
                "first_name": "Adena",
                "last_name": "Cunningham",
                "email": "turpis.egestas@google.net",
                "city": "Limoges",
                "age": 38,
                "gender": "male",
            },
            {
                "first_name": "MacKenzie",
                "last_name": "Bauer",
                "email": "nunc.nulla.vulputate@yahoo.ca",
                "city": "Saint-Malo",
                "age": 22,
                "gender": "male",
            },
            {
                "first_name": "Madeline",
                "last_name": "Dyer",
                "email": "tincidunt.neque@protonmail.net",
                "city": "Saint-Malo",
                "age": 55,
                "gender": "female",
            },
            {
                "first_name": "Walker",
                "last_name": "Douglas",
                "email": "eu.arcu@outlook.com",
                "city": "Pontarlier",
                "age": 33,
                "gender": "female",
            },
            {
                "first_name": "Quail",
                "last_name": "Stuart",
                "email": "felis.purus@protonmail.ca",
                "city": "Montluçon",
                "age": 38,
                "gender": "male",
            },
            {
                "first_name": "Tana",
                "last_name": "ONeill",
                "email": "quam@google.com",
                "city": "Aulnay-sous-Bois",
                "age": 42,
                "gender": "male",
            },
            {
                "first_name": "Rosalyn",
                "last_name": "Grant",
                "email": "ultrices@outlook.ca",
                "city": "Caen",
                "age": 57,
                "gender": "female",
            },
            {
                "first_name": "Nomlanga",
                "last_name": "Silva",
                "email": "vel.lectus@hotmail.couk",
                "city": "Vannes",
                "age": 52,
                "gender": "female",
            },
            {
                "first_name": "Preston",
                "last_name": "Medina",
                "email": "ac@icloud.couk",
                "city": "Montbéliard",
                "age": 59,
                "gender": "male",
            },
            {
                "first_name": "Jerome",
                "last_name": "Hayden",
                "email": "sed.turpis@aol.org",
                "city": "Béziers",
                "age": 37,
                "gender": "male",
            },
            {
                "first_name": "Nell",
                "last_name": "Collins",
                "email": "nisi.magna.sed@aol.net",
                "city": "Strasbourg",
                "age": 33,
                "gender": "female",
            },
            {
                "first_name": "Elvis",
                "last_name": "Bernard",
                "email": "cum.sociis@yahoo.couk",
                "city": "Alençon",
                "age": 31,
                "gender": "female",
            },
            {
                "first_name": "Boris",
                "last_name": "Reese",
                "email": "donec.elementum@google.com",
                "city": "Limoges",
                "age": 21,
                "gender": "male",
            },
            {
                "first_name": "Alec",
                "last_name": "Foster",
                "email": "mauris.morbi.non@protonmail.net",
                "city": "Bastia",
                "age": 30,
                "gender": "male",
            },
        ]

        try:
            with transaction.atomic():
                superuser = User.objects.create(
                    username="beesbusy", email="admin@beesbusy.com"
                )
                superuser.set_password("admin")
                superuser.is_superuser = True
                superuser.save()

                for user in data:
                    new_user = User.objects.create(
                        username=f'{user["first_name"][0].lower()}{user["last_name"].lower()}',
                        first_name=user["first_name"],
                        last_name=user["last_name"],
                        email=user["email"],
                    )
                    profile = new_user.profile
                    profile.age = user["age"]
                    profile.gender = user["gender"]
                    profile.city = user["city"]
                    profile.save()
        except Exception as e:
            print(e)
            pass

    operations = [
        migrations.RunPython(add_data),
    ]
